from __future__ import annotations

import argparse
from pathlib import Path
from zipfile import ZipFile

EXPECTED_MANIFESTS = 35
INCOMPLETE_FAMILIES = {
    "pwc_fb15k_237_dabr",
    "pwc_food_101_mano_tiny",
    "pwc_hme100k_ical",
    "pwc_imagenet_10_dpac",
    "pwc_istd_rasm",
}


def verify(wheel: Path) -> None:
    with ZipFile(wheel) as archive:
        names = archive.namelist()
    manifests = {
        name.split("/")[1]
        for name in names
        if name.startswith("deltamlbench/pwc_") and name.endswith("/manifest.yaml")
    }
    packaged_families = {
        name.split("/")[1]
        for name in names
        if name.startswith("deltamlbench/pwc_") and len(name.split("/")) > 2
    }
    if len(manifests) != EXPECTED_MANIFESTS:
        raise SystemExit(
            f"wheel must contain {EXPECTED_MANIFESTS} active manifests; found {len(manifests)}"
        )
    leaked = sorted(INCOMPLETE_FAMILIES & packaged_families)
    if leaked:
        raise SystemExit(f"wheel contains incomplete families: {leaked}")
    compiled = [name for name in names if name.endswith((".pyc", ".pyo"))]
    if compiled:
        raise SystemExit(f"wheel contains generated bytecode: {compiled}")
    print(f"Verified {wheel}: {len(manifests)} active families")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("wheel", type=Path)
    args = parser.parse_args()
    verify(args.wheel)


if __name__ == "__main__":
    main()
